CREATE TABLESPACE "GODEWIND" 
    LOGGING 
    DATAFILE 'D:\oracle\oradata\GODEWIND.ora' SIZE 40M
   AUTOEXTEND
    ON NEXT  100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT  AUTO ;
  
  CREATE USER "GODEWIND"  PROFILE "DEFAULT" 
    IDENTIFIED BY "GODEWIND" DEFAULT TABLESPACE "GODEWIND" 
    ACCOUNT UNLOCK;
GRANT "CONNECT" TO "GODEWIND";
GRANT "DBA" TO "GODEWIND"

CREATE TABLE "GODEWIND"."NEWS" 
   (  "ID" VARCHAR2(50), 
  "TITLE" VARCHAR2(100), 
  "CONTENT" CLOB, 
  "SUMMARY" CLOB, 
  "CREATETIME" DATE, 
  "CREATEUSER" VARCHAR2(100), 
  "URL" VARCHAR2(500), 
  "TYPE" NUMBER, 
  "ISHOT" NUMBER, 
  "FILENAME" VARCHAR2(100), 
   CONSTRAINT "NEWS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GODEWIND"  ENABLE
   );
  CREATE TABLE "GODEWIND"."T_USER" 
   (  "ID" VARCHAR2(50) NOT NULL ENABLE, 
  "USERNAME" VARCHAR2(100), 
  "PASSWORD" VARCHAR2(100), 
  "CREATETIME" DATE, 
  "CREATEUSER" VARCHAR2(100), 
   CONSTRAINT "USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GODEWIND"  ENABLE
   );