CREATE TABLESPACE "GODEWIND" 
    LOGGING 
    DATAFILE 'D:\oracle\oradata\GODEWIND.ora' SIZE 40M
   AUTOEXTEND
    ON NEXT  100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT  AUTO ;
  
  CREATE USER "GODEWIND"  PROFILE "DEFAULT" 
    IDENTIFIED BY "GODEWIND" DEFAULT TABLESPACE "GODEWIND" 
    ACCOUNT UNLOCK;
GRANT "CONNECT" TO "GODEWIND";
GRANT "DBA" TO "GODEWIND"